#:kivy 1.2.0

<MainWidget>:
    BoxLayout:
        padding: ('30dp', '30dp', '30dp', '30dp')
        size:root.width,root.height
        orientation:'vertical'
        BoxLayout:
            orientation:'vertical'
            spacing: '0dp'
            Label:
                text:'asdasdsa'
            FileBrowser:
                
            

        Button:
            text:'saidas'
        Button:
            text:'saidas'