# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProcuradorExcel.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(783, 562)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setStyleSheet("QWidget{\n"
"    background-color:#32204f;\n"
"    color: white;\n"
"}\n"
"\n"
"QScrollArea{\n"
"    border: none;\n"
"}\n"
"\n"
"QListWidget{\n"
"    background-color: #FFFDED;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    background-color: #FFFDED;\n"
"    padding:8px;\n"
"    \n"
"    \n"
"}\n"
"\n"
"QMenuBar{\n"
"    background-color: #201335;    \n"
"    border-bottom: 1px solid white; \n"
"}\n"
"QMenu{\n"
"    background-color: #201335;    \n"
"}\n"
"\n"
"QPushButton{\n"
"    background-color: #093824;\n"
"    padding: 12px;\n"
"    margin-bottom: 8px;\n"
"    margin-right: 8px;\n"
"    border-radius: 10px;\n"
"    border: 1px solid rgba(255, 255, 255,.5);\n"
"    cursor: pointer;\n"
"}\n"
"QPushButton::hover{\n"
"    border: 1px solid white;\n"
"    background-color: #032115;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 765, 523))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setContentsMargins(30, -1, 30, -1)
        self.gridLayout.setHorizontalSpacing(30)
        self.gridLayout.setVerticalSpacing(40)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.widget_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_2.setStyleSheet("background-color: #201335;\n"
"padding: 12px;\n"
"border-radius: 10px;")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_5.addWidget(self.label_3)
        self.listPalavras = QtWidgets.QListWidget(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listPalavras.sizePolicy().hasHeightForWidth())
        self.listPalavras.setSizePolicy(sizePolicy)
        self.listPalavras.setStyleSheet("background-color: #FFFDED;\n"
"color: black;")
        self.listPalavras.setObjectName("listPalavras")
        self.verticalLayout_5.addWidget(self.listPalavras)
        self.gridLayout_4.addWidget(self.widget_2, 1, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_4, 3, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setStyleSheet("background-color: #201335;\n"
"padding: 12px;\n"
"border-radius: 10px;")
        self.widget.setObjectName("widget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.listFicheiros = QtWidgets.QListWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listFicheiros.sizePolicy().hasHeightForWidth())
        self.listFicheiros.setSizePolicy(sizePolicy)
        self.listFicheiros.setStyleSheet("background-color: #FFFDED;\n"
"color: black;\n"
"")
        self.listFicheiros.setTextElideMode(QtCore.Qt.ElideLeft)
        self.listFicheiros.setObjectName("listFicheiros")
        self.verticalLayout_4.addWidget(self.listFicheiros)
        self.verticalLayout_2.addWidget(self.widget)
        self.verticalLayout_2.setStretch(0, 1)
        self.gridLayout.addLayout(self.verticalLayout_2, 2, 0, 1, 1)
        self.btnPesquisar = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnPesquisar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnPesquisar.setObjectName("btnPesquisar")
        self.gridLayout.addWidget(self.btnPesquisar, 4, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btnAdicionarFicheiro = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnAdicionarFicheiro.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAdicionarFicheiro.setObjectName("btnAdicionarFicheiro")
        self.verticalLayout_3.addWidget(self.btnAdicionarFicheiro)
        self.btnRemoverFicheiro = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnRemoverFicheiro.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnRemoverFicheiro.setObjectName("btnRemoverFicheiro")
        self.verticalLayout_3.addWidget(self.btnRemoverFicheiro)
        self.gridLayout.addLayout(self.verticalLayout_3, 2, 1, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.txtPalavra = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txtPalavra.sizePolicy().hasHeightForWidth())
        self.txtPalavra.setSizePolicy(sizePolicy)
        self.txtPalavra.setStyleSheet("color: black;")
        self.txtPalavra.setObjectName("txtPalavra")
        self.gridLayout_3.addWidget(self.txtPalavra, 1, 1, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.btnAdicionarPalavra = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnAdicionarPalavra.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAdicionarPalavra.setObjectName("btnAdicionarPalavra")
        self.gridLayout_2.addWidget(self.btnAdicionarPalavra, 0, 0, 1, 1)
        self.btnAlterarPalavra = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnAlterarPalavra.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAlterarPalavra.setObjectName("btnAlterarPalavra")
        self.gridLayout_2.addWidget(self.btnAlterarPalavra, 0, 2, 1, 1)
        self.btnRemoverPalavra = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.btnRemoverPalavra.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnRemoverPalavra.setObjectName("btnRemoverPalavra")
        self.gridLayout_2.addWidget(self.btnRemoverPalavra, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 1, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_3, 3, 0, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout.addWidget(self.widget_3, 1, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 783, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionSair = QtWidgets.QAction(MainWindow)
        self.actionSair.setObjectName("actionSair")
        self.menuFile.addAction(self.actionAbout)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionSair)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Palavras a Procurar"))
        self.label_2.setText(_translate("MainWindow", "Ficheiros de procura"))
        self.btnPesquisar.setText(_translate("MainWindow", "Pesquisar"))
        self.btnAdicionarFicheiro.setText(_translate("MainWindow", "Adicionar Ficheiro"))
        self.btnRemoverFicheiro.setText(_translate("MainWindow", "Remover Ficheiro"))
        self.btnAdicionarPalavra.setText(_translate("MainWindow", "Adicionar Palavra"))
        self.btnAlterarPalavra.setText(_translate("MainWindow", "Alterar Palavra"))
        self.btnRemoverPalavra.setText(_translate("MainWindow", "Remover Palavra"))
        self.label.setText(_translate("MainWindow", "Palavra ou frase que deseja procurar:"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionSair.setText(_translate("MainWindow", "Sair"))
